function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(__init__)})
    precompile(Tuple{typeof(gtk_main)})
    precompile(Tuple{Type{GtkWindow},String})
    precompile(Tuple{Type{GtkMenu}})
    precompile(Tuple{Type{GtkMenuItem},String})
    precompile(Tuple{Type{GtkFrameLeaf},Ptr{GObject}})
    precompile(Tuple{Type{GtkBox},Symbol})
    precompile(Tuple{Type{GtkButtonLeaf},Ptr{GObject}})
    precompile(Tuple{Type{GtkToolButton},String})
    precompile(Tuple{typeof(signal_emit),GtkCanvas,String,Type,GdkEventScroll})
    precompile(Tuple{typeof(signal_emit),GtkCanvas,String,Type,GdkEventMotion})
    precompile(Tuple{typeof(signal_emit),GtkCanvas,String,Type,GdkEventButton})
    precompile(Tuple{typeof(signal_emit),GtkEntryLeaf,Symbol,Type})
    precompile(Tuple{typeof(signal_connect),Function,GtkComboBoxTextLeaf,Symbol})
    precompile(Tuple{typeof(setindex!),Dict{Union{WeakRef, GObject},Bool},Bool,GtkTextBufferLeaf})
    precompile(Tuple{typeof(notify_realize),Ptr{GObject},GtkCanvas})
end
